//------------------------------------------------------------------------------
// <auto-generated>
//     This file mirrors Assets/Scripts/Framework/InputSystem/Config/GameInputActions.inputactions.
//     It was simplified by hand so repository code can compile before Unity regenerates it.
//     If the inputactions asset is regenerated by Unity, this file can be replaced by the generated version.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine.InputSystem;

namespace Game.Framework
{
    public sealed class GameInputActions : IDisposable
    {
        public InputActionAsset asset { get; }

        private readonly InputActionMap commonMap;
        private readonly InputActionMap gameplayMap;
        private readonly InputActionMap uiMap;
        private readonly InputActionMap buildMap;
        private readonly InputActionMap dialogueMap;

        private readonly InputAction commonPointerPosition;
        private readonly InputAction commonPointerDelta;
        private readonly InputAction commonScroll;
        private readonly InputAction commonPause;

        private readonly InputAction gameplayMove;
        private readonly InputAction gameplayLook;
        private readonly InputAction gameplayJump;
        private readonly InputAction gameplaySelect;
        private readonly InputAction gameplayAttackCommand;
        private readonly InputAction gameplayCancel;
        private readonly InputAction gameplayInteract;
        private readonly InputAction gameplaySprint;

        private readonly InputAction uiSubmit;
        private readonly InputAction uiCancel;

        private readonly InputAction buildMove;
        private readonly InputAction buildLook;
        private readonly InputAction buildPlace;
        private readonly InputAction buildRemove;
        private readonly InputAction buildRotate;
        private readonly InputAction buildCancel;

        private readonly InputAction dialogueContinue;
        private readonly InputAction dialogueSkip;
        private readonly InputAction dialogueCancel;

        public CommonActions Common { get; }
        public GameplayActions Gameplay { get; }
        public UIActions UI { get; }
        public BuildActions Build { get; }
        public DialogueActions Dialogue { get; }

        public GameInputActions()
        {
            asset = ScriptableObject.CreateInstance<InputActionAsset>();
            asset.name = "GameInputActions";

            commonMap = new InputActionMap("Common");
            gameplayMap = new InputActionMap("Gameplay");
            uiMap = new InputActionMap("UI");
            buildMap = new InputActionMap("Build");
            dialogueMap = new InputActionMap("Dialogue");

            asset.AddActionMap(commonMap);
            asset.AddActionMap(gameplayMap);
            asset.AddActionMap(uiMap);
            asset.AddActionMap(buildMap);
            asset.AddActionMap(dialogueMap);

            commonPointerPosition = commonMap.AddAction("PointerPosition", InputActionType.Value, expectedControlType: "Vector2");
            commonPointerPosition.AddBinding("<Pointer>/position", groups: "Keyboard&Mouse;Touch");

            commonPointerDelta = commonMap.AddAction("PointerDelta", InputActionType.Value, expectedControlType: "Vector2");
            commonPointerDelta.AddBinding("<Pointer>/delta", groups: "Keyboard&Mouse;Touch");

            commonScroll = commonMap.AddAction("Scroll", InputActionType.Value, expectedControlType: "Vector2");
            commonScroll.AddBinding("<Mouse>/scroll", groups: "Keyboard&Mouse");

            commonPause = commonMap.AddAction("Pause", InputActionType.Button, expectedControlType: "Button");
            commonPause.AddBinding("<Keyboard>/escape", groups: "Keyboard&Mouse");
            commonPause.AddBinding("<Gamepad>/start", groups: "Gamepad");

            gameplayMove = gameplayMap.AddAction("Move", InputActionType.Value, expectedControlType: "Vector2");
            gameplayMove.AddCompositeBinding("2DVector", groups: "Keyboard&Mouse")
                .With("Up", "<Keyboard>/upArrow")
                .With("Down", "<Keyboard>/downArrow")
                .With("Left", "<Keyboard>/leftArrow")
                .With("Right", "<Keyboard>/rightArrow");
            gameplayMove.AddBinding("<Gamepad>/leftStick", groups: "Gamepad");

            gameplayLook = gameplayMap.AddAction("Look", InputActionType.Value, expectedControlType: "Vector2");
            gameplayLook.AddBinding("<Mouse>/delta", groups: "Keyboard&Mouse");
            gameplayLook.AddBinding("<Gamepad>/rightStick", groups: "Gamepad");

            gameplayJump = gameplayMap.AddAction("Jump", InputActionType.Button, expectedControlType: "Button");
            gameplayJump.AddBinding("<Keyboard>/space", groups: "Keyboard&Mouse");
            gameplayJump.AddBinding("<Gamepad>/buttonSouth", groups: "Gamepad");

            gameplaySelect = gameplayMap.AddAction("Select", InputActionType.Button, expectedControlType: "Button");
            gameplaySelect.AddBinding("<Mouse>/leftButton", groups: "Keyboard&Mouse");
            gameplaySelect.AddBinding("<Touchscreen>/primaryTouch/tap", groups: "Touch");
            gameplaySelect.AddBinding("<Gamepad>/buttonSouth", groups: "Gamepad");

            gameplayAttackCommand = gameplayMap.AddAction("AttackCommand", InputActionType.Button, expectedControlType: "Button");
            gameplayAttackCommand.AddBinding("<Keyboard>/a", groups: "Keyboard&Mouse");
            gameplayAttackCommand.AddBinding("<Gamepad>/rightTrigger", groups: "Gamepad");

            gameplayCancel = gameplayMap.AddAction("Cancel", InputActionType.Button, expectedControlType: "Button");
            gameplayCancel.AddBinding("<Mouse>/rightButton", groups: "Keyboard&Mouse");
            gameplayCancel.AddBinding("<Keyboard>/escape", groups: "Keyboard&Mouse");
            gameplayCancel.AddBinding("<Gamepad>/buttonEast", groups: "Gamepad");

            gameplayInteract = gameplayMap.AddAction("Interact", InputActionType.Button, expectedControlType: "Button");
            gameplayInteract.AddBinding("<Keyboard>/e", groups: "Keyboard&Mouse");
            gameplayInteract.AddBinding("<Gamepad>/buttonWest", groups: "Gamepad");

            gameplaySprint = gameplayMap.AddAction("Sprint", InputActionType.Button, expectedControlType: "Button");
            gameplaySprint.AddBinding("<Keyboard>/leftShift", groups: "Keyboard&Mouse");
            gameplaySprint.AddBinding("<Gamepad>/leftStickPress", groups: "Gamepad");

            uiSubmit = uiMap.AddAction("Submit", InputActionType.Button, expectedControlType: "Button");
            uiSubmit.AddBinding("<Keyboard>/enter", groups: "Keyboard&Mouse");
            uiSubmit.AddBinding("<Keyboard>/numpadEnter", groups: "Keyboard&Mouse");
            uiSubmit.AddBinding("<Gamepad>/buttonSouth", groups: "Gamepad");

            uiCancel = uiMap.AddAction("Cancel", InputActionType.Button, expectedControlType: "Button");
            uiCancel.AddBinding("<Keyboard>/escape", groups: "Keyboard&Mouse");
            uiCancel.AddBinding("<Gamepad>/buttonEast", groups: "Gamepad");

            buildMove = buildMap.AddAction("Move", InputActionType.Value, expectedControlType: "Vector2");
            buildMove.AddCompositeBinding("2DVector", groups: "Keyboard&Mouse")
                .With("Up", "<Keyboard>/w")
                .With("Down", "<Keyboard>/s")
                .With("Left", "<Keyboard>/a")
                .With("Right", "<Keyboard>/d");
            buildMove.AddBinding("<Gamepad>/leftStick", groups: "Gamepad");

            buildLook = buildMap.AddAction("Look", InputActionType.Value, expectedControlType: "Vector2");
            buildLook.AddBinding("<Mouse>/delta", groups: "Keyboard&Mouse");
            buildLook.AddBinding("<Gamepad>/rightStick", groups: "Gamepad");

            buildPlace = buildMap.AddAction("Place", InputActionType.Button, expectedControlType: "Button");
            buildPlace.AddBinding("<Mouse>/leftButton", groups: "Keyboard&Mouse");
            buildPlace.AddBinding("<Gamepad>/rightTrigger", groups: "Gamepad");

            buildRemove = buildMap.AddAction("Remove", InputActionType.Button, expectedControlType: "Button");
            buildRemove.AddBinding("<Mouse>/rightButton", groups: "Keyboard&Mouse");
            buildRemove.AddBinding("<Gamepad>/leftTrigger", groups: "Gamepad");

            buildRotate = buildMap.AddAction("Rotate", InputActionType.Button, expectedControlType: "Button");
            buildRotate.AddBinding("<Keyboard>/r", groups: "Keyboard&Mouse");
            buildRotate.AddBinding("<Gamepad>/rightShoulder", groups: "Gamepad");

            buildCancel = buildMap.AddAction("Cancel", InputActionType.Button, expectedControlType: "Button");
            buildCancel.AddBinding("<Keyboard>/escape", groups: "Keyboard&Mouse");
            buildCancel.AddBinding("<Gamepad>/buttonEast", groups: "Gamepad");

            dialogueContinue = dialogueMap.AddAction("Continue", InputActionType.Button, expectedControlType: "Button");
            dialogueContinue.AddBinding("<Keyboard>/space", groups: "Keyboard&Mouse");
            dialogueContinue.AddBinding("<Keyboard>/enter", groups: "Keyboard&Mouse");
            dialogueContinue.AddBinding("<Mouse>/leftButton", groups: "Keyboard&Mouse");
            dialogueContinue.AddBinding("<Gamepad>/buttonSouth", groups: "Gamepad");

            dialogueSkip = dialogueMap.AddAction("Skip", InputActionType.Button, expectedControlType: "Button");
            dialogueSkip.AddBinding("<Keyboard>/leftCtrl", groups: "Keyboard&Mouse");
            dialogueSkip.AddBinding("<Gamepad>/buttonWest", groups: "Gamepad");

            dialogueCancel = dialogueMap.AddAction("Cancel", InputActionType.Button, expectedControlType: "Button");
            dialogueCancel.AddBinding("<Keyboard>/escape", groups: "Keyboard&Mouse");
            dialogueCancel.AddBinding("<Gamepad>/buttonEast", groups: "Gamepad");

            Common = new CommonActions(commonMap, commonPointerPosition, commonPointerDelta, commonScroll, commonPause);
            Gameplay = new GameplayActions(gameplayMap, gameplayMove, gameplayLook, gameplayJump, gameplaySelect, gameplayAttackCommand, gameplayCancel, gameplayInteract, gameplaySprint);
            UI = new UIActions(uiMap, uiSubmit, uiCancel);
            Build = new BuildActions(buildMap, buildMove, buildLook, buildPlace, buildRemove, buildRotate, buildCancel);
            Dialogue = new DialogueActions(dialogueMap, dialogueContinue, dialogueSkip, dialogueCancel);
        }

        public void Dispose()
        {
            asset.Disable();
            UnityEngine.Object.Destroy(asset);
        }

        public readonly struct CommonActions
        {
            private readonly InputActionMap map;
            public readonly InputAction PointerPosition;
            public readonly InputAction PointerDelta;
            public readonly InputAction Scroll;
            public readonly InputAction Pause;

            public CommonActions(InputActionMap map, InputAction pointerPosition, InputAction pointerDelta, InputAction scroll, InputAction pause)
            {
                this.map = map;
                PointerPosition = pointerPosition;
                PointerDelta = pointerDelta;
                Scroll = scroll;
                Pause = pause;
            }

            public void Enable()
            {
                map.Enable();
            }

            public void Disable()
            {
                map.Disable();
            }
        }

        public readonly struct GameplayActions
        {
            private readonly InputActionMap map;
            public readonly InputAction Move;
            public readonly InputAction Look;
            public readonly InputAction Jump;
            public readonly InputAction Select;
            public readonly InputAction AttackCommand;
            public readonly InputAction Cancel;
            public readonly InputAction Interact;
            public readonly InputAction Sprint;

            public GameplayActions(InputActionMap map, InputAction move, InputAction look, InputAction jump, InputAction select, InputAction attackCommand, InputAction cancel, InputAction interact, InputAction sprint)
            {
                this.map = map;
                Move = move;
                Look = look;
                Jump = jump;
                Select = select;
                AttackCommand = attackCommand;
                Cancel = cancel;
                Interact = interact;
                Sprint = sprint;
            }

            public void Enable()
            {
                map.Enable();
            }

            public void Disable()
            {
                map.Disable();
            }
        }

        public readonly struct UIActions
        {
            private readonly InputActionMap map;
            public readonly InputAction Submit;
            public readonly InputAction Cancel;

            public UIActions(InputActionMap map, InputAction submit, InputAction cancel)
            {
                this.map = map;
                Submit = submit;
                Cancel = cancel;
            }

            public void Enable()
            {
                map.Enable();
            }

            public void Disable()
            {
                map.Disable();
            }
        }

        public readonly struct BuildActions
        {
            private readonly InputActionMap map;
            public readonly InputAction Move;
            public readonly InputAction Look;
            public readonly InputAction Place;
            public readonly InputAction Remove;
            public readonly InputAction Rotate;
            public readonly InputAction Cancel;

            public BuildActions(InputActionMap map, InputAction move, InputAction look, InputAction place, InputAction remove, InputAction rotate, InputAction cancel)
            {
                this.map = map;
                Move = move;
                Look = look;
                Place = place;
                Remove = remove;
                Rotate = rotate;
                Cancel = cancel;
            }

            public void Enable()
            {
                map.Enable();
            }

            public void Disable()
            {
                map.Disable();
            }
        }

        public readonly struct DialogueActions
        {
            private readonly InputActionMap map;
            public readonly InputAction Continue;
            public readonly InputAction Skip;
            public readonly InputAction Cancel;

            public DialogueActions(InputActionMap map, InputAction continueAction, InputAction skip, InputAction cancel)
            {
                this.map = map;
                Continue = continueAction;
                Skip = skip;
                Cancel = cancel;
            }

            public void Enable()
            {
                map.Enable();
            }

            public void Disable()
            {
                map.Disable();
            }
        }
    }
}
